import { Calculator, Sparkles, Code, Scale, Receipt, QrCode } from 'lucide-react';

export interface ToolItem {
  id: string;
  slug: string;
  title: string;
  shortTitle: string;
  category: 'finance_tax' | 'retainer_agency' | 'ai_copy' | 'contracts_legal' | 'developer_embed' | 'payments_upi' | 'pdf_tools' | 'sheets_tools' | 'image_tools';
  categoryLabel: string;
  badge: string;
  badgeColor: string;
  tagline: string;
  description: string;
  iconName: string;
  highlights: string[];
  runs: string;
  inputPlaceholder: string;
}

export interface ToolCategoryBlock {
  id: string;
  title: string;
  subtitle: string;
  badgeTag: string;
  iconName: string;
  cardBg: string;
  iconBg: string;
  accentText: string;
  borderColor: string;
  borderHover: string;
  badgeBg: string;
  featuredToolName: string;
  featuredToolSlug: string;
}

export const TOOL_CATEGORY_BLOCKS: ToolCategoryBlock[] = [
  {
    id: 'image_tools',
    title: 'Image Tools',
    subtitle: 'Compress, Resize, Background & HEIC',
    badgeTag: 'In-RAM Canvas',
    iconName: 'ImageIcon',
    cardBg: 'bg-gradient-to-b from-[#EFF6FF] via-[#DBEAFE] to-white',
    iconBg: 'bg-blue-600 text-white shadow-[0_6px_16px_rgba(37,99,235,0.25)]',
    accentText: 'text-blue-600',
    borderColor: 'border-blue-100/90',
    borderHover: 'hover:border-blue-400 hover:shadow-[0_16px_36px_rgba(37,99,235,0.12)]',
    badgeBg: 'bg-blue-100/90 text-blue-700',
    featuredToolName: 'Compress Image',
    featuredToolSlug: 'compress-image',
  },
  {
    id: 'sheets_tools',
    title: 'Sheets & Excel',
    subtitle: 'Formulas, VLOOKUP & Converters',
    badgeTag: 'AI & Data',
    iconName: 'Table',
    cardBg: 'bg-gradient-to-b from-[#ECFDF5] via-[#D1FAE5] to-white',
    iconBg: 'bg-emerald-600 text-white shadow-[0_6px_16px_rgba(5,150,105,0.25)]',
    accentText: 'text-emerald-600',
    borderColor: 'border-emerald-100/90',
    borderHover: 'hover:border-emerald-400 hover:shadow-[0_16px_36px_rgba(5,150,105,0.12)]',
    badgeBg: 'bg-emerald-100/90 text-emerald-700',
    featuredToolName: 'Formula Generator',
    featuredToolSlug: 'excel-formula-generator',
  },
  {
    id: 'pdf_tools',
    title: 'PDF Tools',
    subtitle: 'Merge, Split, eSign & Images',
    badgeTag: 'Client-Side',
    iconName: 'FileText',
    cardBg: 'bg-gradient-to-b from-[#FEF2F2] via-[#FEE2E2] to-white',
    iconBg: 'bg-rose-600 text-white shadow-[0_6px_16px_rgba(225,29,72,0.25)]',
    accentText: 'text-rose-600',
    borderColor: 'border-rose-100/90',
    borderHover: 'hover:border-rose-400 hover:shadow-[0_16px_36px_rgba(225,29,72,0.12)]',
    badgeBg: 'bg-rose-100/90 text-rose-700',
    featuredToolName: 'Merge PDF Files',
    featuredToolSlug: 'merge-pdf',
  },
  {
    id: 'finance_tax',
    title: 'GST & Tax Math',
    subtitle: '18% SAC 9983 & CGST/SGST',
    badgeTag: 'Tax Engine',
    iconName: 'Calculator',
    cardBg: 'bg-gradient-to-b from-[#EEF4FF] via-[#E4EEFE] to-white',
    iconBg: 'bg-indigo-600 text-white shadow-[0_6px_16px_rgba(79,70,229,0.25)]',
    accentText: 'text-indigo-600',
    borderColor: 'border-indigo-100/90',
    borderHover: 'hover:border-indigo-400 hover:shadow-[0_16px_36px_rgba(79,70,229,0.12)]',
    badgeBg: 'bg-indigo-100/90 text-indigo-700',
    featuredToolName: 'GST Calculator',
    featuredToolSlug: 'gst-calculator',
  },
  {
    id: 'retainer_agency',
    title: 'Agency Retainers',
    subtitle: 'Scope Buffers & Hourly Rates',
    badgeTag: 'Pricing Model',
    iconName: 'Receipt',
    cardBg: 'bg-gradient-to-b from-[#FFF7ED] via-[#FFEDD5] to-white',
    iconBg: 'bg-orange-500 text-white shadow-[0_6px_16px_rgba(249,115,22,0.25)]',
    accentText: 'text-orange-600',
    borderColor: 'border-orange-100/90',
    borderHover: 'hover:border-orange-400 hover:shadow-[0_16px_36px_rgba(249,115,22,0.12)]',
    badgeBg: 'bg-orange-100/90 text-orange-700',
    featuredToolName: 'Retainer Math',
    featuredToolSlug: 'retainer-calculator',
  },
  {
    id: 'contracts_legal',
    title: 'Legal Contracts',
    subtitle: 'Section 10A IT Act Clauses',
    badgeTag: 'Legal Vault',
    iconName: 'Scale',
    cardBg: 'bg-gradient-to-b from-[#F0F9FF] via-[#E0F2FE] to-white',
    iconBg: 'bg-blue-600 text-white shadow-[0_6px_16px_rgba(37,99,235,0.25)]',
    accentText: 'text-blue-600',
    borderColor: 'border-blue-100/90',
    borderHover: 'hover:border-blue-400 hover:shadow-[0_16px_36px_rgba(37,99,235,0.12)]',
    badgeBg: 'bg-blue-100/90 text-blue-700',
    featuredToolName: 'Contract Builder',
    featuredToolSlug: 'contract-builder',
  },
  {
    id: 'ai_copy',
    title: 'Studio AI Copy',
    subtitle: 'Brochures & Brief Prompts',
    badgeTag: 'AI Studio',
    iconName: 'Sparkles',
    cardBg: 'bg-gradient-to-b from-[#FFF1F2] via-[#FFE4E6] to-white',
    iconBg: 'bg-rose-500 text-white shadow-[0_6px_16px_rgba(244,63,94,0.25)]',
    accentText: 'text-rose-600',
    borderColor: 'border-rose-100/90',
    borderHover: 'hover:border-rose-400 hover:shadow-[0_16px_36px_rgba(244,63,94,0.12)]',
    badgeBg: 'bg-rose-100/90 text-rose-700',
    featuredToolName: 'Listing AI',
    featuredToolSlug: 'listing-ai',
  },
  {
    id: 'payments_upi',
    title: 'UPI 2.0 Invoicing',
    subtitle: 'Zero Fee Payment Links',
    badgeTag: '0% Gateway',
    iconName: 'QrCode',
    cardBg: 'bg-gradient-to-b from-[#FAF5FF] via-[#F3E8FF] to-white',
    iconBg: 'bg-purple-600 text-white shadow-[0_6px_16px_rgba(147,51,234,0.25)]',
    accentText: 'text-purple-600',
    borderColor: 'border-purple-100/90',
    borderHover: 'hover:border-purple-400 hover:shadow-[0_16px_36px_rgba(147,51,234,0.12)]',
    badgeBg: 'bg-purple-100/90 text-purple-700',
    featuredToolName: 'Dynamic UPI QR',
    featuredToolSlug: 'upi-qr-generator',
  },
  {
    id: 'developer_embed',
    title: 'Embed Widgets',
    subtitle: 'Framer & Webflow Forms',
    badgeTag: 'Developer',
    iconName: 'Code',
    cardBg: 'bg-gradient-to-b from-[#F0FDFA] via-[#CCFBF1] to-white',
    iconBg: 'bg-teal-600 text-white shadow-[0_6px_16px_rgba(13,148,136,0.25)]',
    accentText: 'text-teal-600',
    borderColor: 'border-teal-100/90',
    borderHover: 'hover:border-teal-400 hover:shadow-[0_16px_36px_rgba(13,148,136,0.12)]',
    badgeBg: 'bg-teal-100/90 text-teal-700',
    featuredToolName: 'Embed Builder',
    featuredToolSlug: 'embed-builder',
  },
];

export const TOOL_CATEGORIES = [
  { id: 'all', label: 'All Tools', count: 55 },
  { id: 'pdf_tools', label: 'PDF Tools', count: 28 },
  { id: 'sheets_tools', label: 'Sheets & Excel', count: 9 },
  { id: 'image_tools', label: 'Image Tools', count: 12 },
  { id: 'finance_tax', label: 'Finance & Tax', count: 2 },
  { id: 'contracts_legal', label: 'Contracts & Legal', count: 1 },
  { id: 'ai_copy', label: 'AI & Copywriting', count: 1 },
  { id: 'developer_embed', label: 'Developer & Embeds', count: 2 },
];

export const TOOLS_DATA: ToolItem[] = [
  {
    id: 'gst-calculator',
    slug: 'gst-calculator',
    title: 'Indian GST & B2B Tax Calculator',
    shortTitle: 'GST Tax Calculator',
    category: 'finance_tax',
    categoryLabel: 'Finance & Tax',
    badge: 'Popular in India',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Instant 18%, 12%, 5%, 28% tax breakdown with CGST/SGST vs IGST segregation.',
    description: 'Calculate GST inclusive and exclusive pricing, split intra-state vs inter-state tax liabilities, and generate compliant breakdown summaries for your client proposals.',
    iconName: 'Calculator',
    highlights: ['18% SAC 9983 Support', 'CGST & SGST 50/50 Split', 'IGST Inter-State Toggle', '1-Click Breakdown Copy'],
    runs: 'Zero Login Required',
    inputPlaceholder: '₹50,000',
  },
  {
    id: 'retainer-calculator',
    slug: 'retainer-calculator',
    title: 'Service Retainer & Scope Buffer Calculator',
    shortTitle: 'Retainer Math Calculator',
    category: 'finance_tax',
    categoryLabel: 'Finance & Tax',
    badge: 'Agency Tool',
    badgeColor: 'bg-blue-50 text-blue-700 border border-blue-200/80',
    tagline: 'Calculate optimal monthly agency retainer tiers and billable hourly baseline rates.',
    description: 'Input your revenue targets, billable client capacity, and team overheads to calculate sustainable monthly retainer packages with automatic 20% scope creep buffers.',
    iconName: 'Receipt',
    highlights: ['Hourly to Retainer Conversion', '20% Scope Creep Buffer', 'Capacity Utilization Math', 'Client Tier Allocation'],
    runs: 'Zero Login Required',
    inputPlaceholder: '₹3,00,000 / mo',
  },
  {
    id: 'contract-builder',
    slug: 'contract-builder',
    title: 'Indian IT Act 2000 Contract Clause Builder',
    shortTitle: 'Contract Clause Builder',
    category: 'contracts_legal',
    categoryLabel: 'Contracts & Legal',
    badge: 'IT Act 2000 Compliant',
    badgeColor: 'bg-slate-100 text-slate-800 border border-slate-200/80',
    tagline: 'Generate legally binding contract clauses, milestone escrow terms, and NDAs.',
    description: 'Build customized Indian legal agreements with Section 10A digital signature recognition, SHA-256 tamper-evident integrity clauses, and 18% GST tax provisions.',
    iconName: 'Scale',
    highlights: ['Section 10A Electronic Signatures', 'Scope Lock & Milestone Escrow', 'IP & Copyright Assignment', 'Mutual Non-Disclosure Terms'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Client: Acme Corp, Retainer: ₹1,50,000...',
  },
  {
    id: 'listing-ai',
    slug: 'listing-ai',
    title: 'Real Estate & Studio Listing AI Generator',
    shortTitle: 'Listing AI Generator',
    category: 'ai_copy',
    categoryLabel: 'AI & Copywriting',
    badge: 'AI Powered',
    badgeColor: 'bg-purple-50 text-purple-700 border border-purple-200/80',
    tagline: 'Turn raw property or shoot details into high-converting marketing copy and client briefs.',
    description: 'Leverage domain-trained AI prompts to generate luxury real estate brochures, Instagram captions, commercial shoot briefs, and client welcome decks in seconds.',
    iconName: 'Sparkles',
    highlights: ['3 Output Formats', 'Commercial & Residential Modes', 'Tone Tuning (Luxury / Minimal)', 'Multi-Platform Export'],
    runs: 'Zero Login Required',
    inputPlaceholder: '3BHK Sea-Facing Penthouse, Bandra West...',
  },
  {
    id: 'upi-qr-generator',
    slug: 'upi-qr-generator',
    title: 'Dynamic UPI QR & Payment Intent Generator',
    shortTitle: 'UPI QR Generator',
    category: 'developer_embed',
    categoryLabel: 'Developer & Embeds',
    badge: 'UPI 2.0 Ready',
    badgeColor: 'bg-teal-50 text-teal-700 border border-teal-200/80',
    tagline: 'Generate instant UPI QR codes with custom invoice amount, payee VPA & transaction note.',
    description: 'Create zero-fee dynamic UPI payment links and printable QR codes for Indian bank settlements. Compatible with Google Pay, PhonePe, Paytm, and BHIM.',
    iconName: 'QrCode',
    highlights: ['Zero Payment Gateway Fees (0%)', 'Exact Invoice Amount Embedding', 'Instant Client-Side QR Render', 'PNG & SVG Download'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'business@okhdfcbank',
  },
  {
    id: 'embed-builder',
    slug: 'embed-builder',
    title: 'Autonomous AI Copilot & Embed Builder',
    shortTitle: 'Embed Widget Builder',
    category: 'developer_embed',
    categoryLabel: 'Developer & Embeds',
    badge: 'Developer Tool',
    badgeColor: 'bg-amber-50 text-amber-700 border border-amber-200/80',
    tagline: 'Generate embeddable AI booking widgets for Framer, Webflow, WordPress & Shopify.',
    description: 'Customize zero-code iframe embeds to capture leads, book call slots, and calculate quotes directly on your marketing site with auto-sync to your Cora workspace.',
    iconName: 'Code',
    highlights: ['Zero-Code iFrame Snippet', 'Framer & Webflow Ready', 'Light / Dark Mode Customization', 'Direct Webhook Integration'],
    runs: 'Zero Login Required',
    inputPlaceholder: '<iframe src="https://heycora.in/embed/..." />',
  },
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    title: 'Merge PDF Files Online Free',
    shortTitle: 'Merge PDF Files',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: '100% Client-Side',
    badgeColor: 'bg-rose-50 text-rose-700 border border-rose-200/80',
    tagline: 'Combine multiple PDF documents into a single organized file in seconds.',
    description: 'Merge invoices, contracts, proposals, and client portfolios with simple drag-and-drop reordering. 100% private and runs entirely in your browser.',
    iconName: 'Files',
    highlights: ['Zero Server Uploads', 'Drag & Drop Page Reorder', 'Instant In-Browser Merge', 'No File Size Limits'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop PDF files here to merge...',
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    title: 'Split & Extract PDF Pages',
    shortTitle: 'Split & Extract PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'Instant Extract',
    badgeColor: 'bg-amber-50 text-amber-700 border border-amber-200/80',
    tagline: 'Separate PDF pages or extract custom page ranges into individual documents.',
    description: 'Extract specific pages, isolate signed execution sheets, or split heavy deliverables into lightweight client PDF packets without quality loss.',
    iconName: 'Scissors',
    highlights: ['Custom Range Extraction', 'Single Page Isolation', '100% In-Browser Engine', 'Instant Zip / File Download'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'e.g. 1-3, 5, 8-10',
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    title: 'Rotate PDF Pages Permanently',
    shortTitle: 'Rotate PDF Pages',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: '90° / 180° / 270°',
    badgeColor: 'bg-blue-50 text-blue-700 border border-blue-200/80',
    tagline: 'Rotate orientation of individual or all pages in your PDF document permanently.',
    description: 'Fix upside-down scans, adjust architectural plan orientation, and align landscape agreements before sending to clients.',
    iconName: 'RotateCw',
    highlights: ['Selective Page Rotation', 'Clockwise & Counter-Clockwise', 'Permanent Metadata Save', 'Zero Cloud Transmission'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Select pages to rotate...',
  },
  {
    id: 'images-to-pdf',
    slug: 'images-to-pdf',
    title: 'Images to PDF Converter (JPG, PNG, WebP)',
    shortTitle: 'Images to PDF Converter',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'High-Res Output',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Convert photos, design mockups, and receipts into a unified high-res PDF.',
    description: 'Bundle shoot photos, invoice receipts, and property site inspections into clean, shareable client PDF decks with margin and orientation controls.',
    iconName: 'ImageIcon',
    highlights: ['JPG, PNG, WebP & HEIC', 'Custom Page Sizing (A4/Letter)', 'Margin & Spacing Controls', 'Lossless Quality Retention'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop photo assets here...',
  },
  {
    id: 'esign-pdf',
    slug: 'esign-pdf',
    title: 'Digital eSign PDF & Contract Signer',
    shortTitle: 'Digital eSign PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'IT Act 2000 Ready',
    badgeColor: 'bg-indigo-50 text-indigo-700 border border-indigo-200/80',
    tagline: 'Draw or type your signature and place it securely on any PDF agreement.',
    description: 'Sign NDAs, client estimates, vendor agreements, and invoices directly in browser with timestamped audit markers.',
    iconName: 'FileCheck',
    highlights: ['Draw or Type Signatures', 'Stamp & Date Placeholders', 'Section 10A IT Act Compliant', 'No Account Required'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Upload document to sign...',
  },
  {
    id: 'watermark-pdf',
    slug: 'watermark-pdf',
    title: 'Add Watermark to PDF Documents',
    shortTitle: 'Add Watermark to PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'Draft & Confidential',
    badgeColor: 'bg-violet-50 text-violet-700 border border-violet-200/80',
    tagline: 'Stamp text or image watermarks across PDF pages with opacity controls.',
    description: 'Protect draft contracts, sensitive client proposals, and preview design proofs with custom diagonal text stamps and confidentiality markers.',
    iconName: 'Stamp',
    highlights: ['Custom Text & Opacity', 'Diagonal & Center Placement', 'Batch Page Watermarking', 'Zero Server File Retention'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'e.g. CONFIDENTIAL / DRAFT',
  },
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    title: 'Compress PDF Online Free',
    shortTitle: 'Compress PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'Popular',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Reduce PDF file size up to 70% in seconds while preserving crisp vector text.',
    description: 'Compress heavy client proposals, pitch decks, and invoices to under 5MB for instant WhatsApp sharing and email attachments. 100% private in-browser execution.',
    iconName: 'Minimize2',
    highlights: ['3 Compression Tiers', 'Up to 70% Size Reduction', 'Live Before/After Metrics', 'Zero Server Uploads'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop PDF file here to compress...',
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    title: 'Word to PDF Converter Online',
    shortTitle: 'Word to PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'New',
    badgeColor: 'bg-blue-50 text-blue-700 border border-blue-200/80',
    tagline: 'Transform raw document text, terms, and drafts into clean typeset A4 PDF files.',
    description: 'Publish memos, client estimates, and agreements into standardized PDF documents with automated word wrapping and clean typography.',
    iconName: 'FileType',
    highlights: ['Automated Word Wrapping', 'Clean A4 Typesetting', 'Standard Font Embeds', 'Instant 1-Click Download'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Paste or upload document text...',
  },
  {
    id: 'number-pdf',
    slug: 'number-pdf',
    title: 'Add Page Numbers to PDF',
    shortTitle: 'Add Page Numbers',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'Custom Headers/Footers',
    badgeColor: 'bg-purple-50 text-purple-700 border border-purple-200/80',
    tagline: 'Stamp automated pagination headers and footers with customizable format and offsets.',
    description: 'Format legal briefs, client contracts, and multi-page technical decks with uniform page numbers (Bottom-Center, Bottom-Right, "Page X of Y").',
    iconName: 'Hash',
    highlights: ['Page X of Y & Numeric Formats', 'Position Presets', 'Custom Starting Page', 'Lossless Vector Stamping'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop PDF to add page numbers...',
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    title: 'Remove Pages from PDF',
    shortTitle: 'Remove Pages',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: '1-Click Delete',
    badgeColor: 'bg-red-50 text-red-700 border border-red-200/80',
    tagline: 'Delete unwanted sheets, blank pages, or outdated appendixes from your PDF.',
    description: 'Select pages to delete or enter custom page spans with visual feedback and export a pristine, compact PDF document in seconds.',
    iconName: 'Trash2',
    highlights: ['Visual Page Chips', 'Custom Range Inputs', 'Instant Re-export', '100% In-Memory'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'e.g. 2, 4-6',
  },
  {
    id: 'ai-pdf-summarizer',
    slug: 'ai-pdf-summarizer',
    title: 'AI PDF Summarizer & Contract Scanner',
    shortTitle: 'AI PDF Summarizer',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'AI Radar',
    badgeColor: 'bg-amber-50 text-amber-700 border border-amber-200/80',
    tagline: 'Scan contracts, find hidden risk clauses, and extract executive summaries in seconds.',
    description: 'Instantly audit commercial proposals and vendor agreements for liabilities, payment schedules, and termination penalties with Cora AI intelligence.',
    iconName: 'Bot',
    highlights: ['Clause Risk Radar', 'Executive Summary', 'Action Item Breakdown', 'Bridge to Cora AI Co-Founder'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop PDF document to inspect...',
  },
  {
    id: 'excel-formula-generator',
    slug: 'excel-formula-generator',
    title: 'AI Excel & Google Sheets Formula Generator',
    shortTitle: 'Formula Generator',
    category: 'sheets_tools',
    categoryLabel: 'Sheets & Excel',
    badge: 'AI Powered',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Translate plain English descriptions into complex, error-free Excel and Google Sheets formulas.',
    description: 'Describe your calculation in plain words (SUMIFS, XLOOKUP, REGEXEXTRACT) and receive instant, syntax-tested formulas with argument breakdowns and copy shortcuts.',
    iconName: 'Sparkles',
    highlights: ['English to Formula AI', 'Syntax Breakdown', 'Excel & Google Sheets Modes', '100% In-Browser'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Describe your formula goal in plain English...',
  },
  {
    id: 'vlookup-generator',
    slug: 'vlookup-generator',
    title: 'Visual VLOOKUP & XLOOKUP Builder',
    shortTitle: 'VLOOKUP Builder',
    category: 'sheets_tools',
    categoryLabel: 'Sheets & Excel',
    badge: 'Visual Builder',
    badgeColor: 'bg-blue-50 text-blue-700 border border-blue-200/80',
    tagline: 'Build accurate VLOOKUP and XLOOKUP formulas interactively without memorizing argument orders.',
    description: 'Configure lookup keys, table arrays, column indices, and fallback IFERROR defaults in an interactive visual editor that generates both classic and modern formulas.',
    iconName: 'Search',
    highlights: ['VLOOKUP & XLOOKUP Support', 'Visual Index Selector', 'IFERROR Guardrails', 'Instant Clipboard Copy'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Configure lookup cell and range...',
  },
  {
    id: 'clean-sheet-data',
    slug: 'clean-sheet-data',
    title: 'Clean & Format Spreadsheet Data',
    shortTitle: 'Clean Sheet Data',
    category: 'sheets_tools',
    categoryLabel: 'Sheets & Excel',
    badge: 'Data Hygiene',
    badgeColor: 'bg-teal-50 text-teal-700 border border-teal-200/80',
    tagline: 'Normalize messy customer sheets, format Indian phone numbers, trim whitespace, and fix dates.',
    description: 'Drop CSV or paste spreadsheet cells to trim irregular spaces, format phone numbers to +91, standardize dates to ISO YYYY-MM-DD, title-case names, and purge ghost rows in browser RAM.',
    iconName: 'Sparkles',
    highlights: ['Phone & Date Normalization', 'Whitespace Trimming', 'Side-by-Side Preview', 'Zero Server Uploads'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop CSV or paste messy tabular data...',
  },
  {
    id: 'csv-to-excel',
    slug: 'csv-to-excel',
    title: 'CSV to Excel Converter (.xlsx)',
    shortTitle: 'CSV to Excel',
    category: 'sheets_tools',
    categoryLabel: 'Sheets & Excel',
    badge: 'Native XML',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Convert CSV and TSV text files into clean, styled Excel workbooks (.xlsx) directly in memory.',
    description: 'Transform raw delimited files into structured, multi-column Excel workbooks with custom worksheet naming and zero server transmission.',
    iconName: 'FileSpreadsheet',
    highlights: ['Instant XML .xlsx Generation', 'Live Table Preview', 'Custom Sheet Name', '100% In-Browser Memory'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop CSV file to convert to Excel...',
  },
  {
    id: 'excel-to-csv',
    slug: 'excel-to-csv',
    title: 'Excel & Sheet to CSV Converter',
    shortTitle: 'Excel to CSV',
    category: 'sheets_tools',
    categoryLabel: 'Sheets & Excel',
    badge: 'RFC 4180',
    badgeColor: 'bg-indigo-50 text-indigo-700 border border-indigo-200/80',
    tagline: 'Convert spreadsheet grids into escaped RFC 4180 standard CSV or TSV files with custom delimiters.',
    description: 'Export spreadsheet rows into commas, semicolons, tabs, or pipes with compliant double-quote escaping and instant 1-click clipboard copying.',
    iconName: 'FileText',
    highlights: ['Custom Delimiter Choice', 'RFC 4180 Escaping', '1-Click Clipboard Copy', 'Zero Cloud Retention'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop CSV or paste spreadsheet grid...',
  },
  {
    id: 'excel-to-json',
    slug: 'excel-to-json',
    title: 'Excel & CSV to JSON Converter',
    shortTitle: 'Excel to JSON',
    category: 'sheets_tools',
    categoryLabel: 'Sheets & Excel',
    badge: 'Developer Tool',
    badgeColor: 'bg-purple-50 text-purple-700 border border-purple-200/80',
    tagline: 'Convert tabular spreadsheet rows into structured JSON objects, 2D arrays, or indexed maps.',
    description: 'Transform CSV and spreadsheet data into formatted, syntax-highlighted JSON with automatic numeric type casting and 1-click download or clipboard copy.',
    iconName: 'Code',
    highlights: ['3 Output Formats', 'Number Coercion', 'Syntax Highlighted Editor', 'Instant .json Download'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop CSV or paste tabular rows...',
  },
  {
    id: 'remove-duplicates-csv',
    slug: 'remove-duplicates-csv',
    title: 'Remove Duplicates from CSV & Sheets',
    shortTitle: 'Remove Duplicates',
    category: 'sheets_tools',
    categoryLabel: 'Sheets & Excel',
    badge: 'Exact Key Match',
    badgeColor: 'bg-rose-50 text-rose-700 border border-rose-200/80',
    tagline: 'Deduplicate spreadsheet rows by specific key columns or entire records with real-time stats.',
    description: 'Select which columns define a duplicate (Email, Mobile, Tax ID) or scan all fields. Get instant metrics on duplicates purged and download pristine CSVs.',
    iconName: 'Filter',
    highlights: ['Column Checklist Matching', 'Case Sensitivity Toggle', 'Live Deduplication Metrics', '100% In-Memory RAM'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop CSV to deduplicate rows...',
  },
  {
    id: 'merge-csv',
    slug: 'merge-csv',
    title: 'Merge Multiple CSV Files',
    shortTitle: 'Merge CSV',
    category: 'sheets_tools',
    categoryLabel: 'Sheets & Excel',
    badge: 'Header Alignment',
    badgeColor: 'bg-amber-50 text-amber-700 border border-amber-200/80',
    tagline: 'Combine dozens of separate CSV spreadsheets into a single consolidated master table.',
    description: 'Drag and drop multiple CSV sheets. Cora automatically aligns column headers, compiles consolidated rows in browser RAM, and exports a unified master spreadsheet.',
    iconName: 'Layers',
    highlights: ['Multi-File Batch Upload', 'Automatic Header Alignment', 'Consolidated Live Preview', 'Zero Server Retention'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop multiple CSV files to merge...',
  },
  {
    id: 'split-csv',
    slug: 'split-csv',
    title: 'Split CSV by Rows or Column Value',
    shortTitle: 'Split CSV',
    category: 'sheets_tools',
    categoryLabel: 'Sheets & Excel',
    badge: 'Dual Mode Split',
    badgeColor: 'bg-cyan-50 text-cyan-700 border border-cyan-200/80',
    tagline: 'Split large CSV files into smaller chunks by row count limit or by unique column categories.',
    description: 'Bypass spreadsheet row limits and CRM batch upload restrictions by chunking files into configurable row sizes or partitioning automatically by column values (City, Status, Vendor).',
    iconName: 'Scissors',
    highlights: ['Split by Row Count', 'Partition by Column Value', 'Individual Batch Downloads', '100% In-Memory'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop large CSV file to split...',
  },
  {
    id: 'compress-image',
    slug: 'compress-image',
    title: 'Compress Image (JPG, PNG, WebP)',
    shortTitle: 'Compress Image',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'Popular',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Reduce JPG, PNG, and WebP file size up to 80% with visual quality and KB target controls.',
    description: 'Compress web assets and portfolio photos in browser memory. Keep vector edges sharp while stripping bloat metadata with instant side-by-side inspection.',
    iconName: 'Minimize2',
    highlights: ['Lossless & Lossy Sliders', 'Exact Target KB Limiter', 'Side-by-Side Zoom Preview', '100% In-Browser RAM'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop JPG, PNG, or WebP to compress...',
  },
  {
    id: 'resize-image',
    slug: 'resize-image',
    title: 'Resize Image Dimensions',
    shortTitle: 'Resize Image',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'Exact Pixels',
    badgeColor: 'bg-blue-50 text-blue-700 border border-blue-200/80',
    tagline: 'Scale image dimensions, DPI, and export preset social sizes with aspect-ratio locking.',
    description: 'Quickly resize photos to exact pixel dimensions, percentage multipliers, or social presets (Instagram, LinkedIn, Twitter/X, YouTube) in pure canvas memory.',
    iconName: 'Crop',
    highlights: ['Social Aspect Presets', 'Aspect Ratio Lock', 'Bicubic High-Res Interpolation', 'Zero Server Uploads'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop image to resize dimensions...',
  },
  {
    id: 'crop-image',
    slug: 'crop-image',
    title: 'Crop Image & Circular Cutout',
    shortTitle: 'Crop Image',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'Visual Framing',
    badgeColor: 'bg-amber-50 text-amber-700 border border-amber-200/80',
    tagline: 'Crop photos with standard aspect ratios, zoom adjustments, and circular avatar masks.',
    description: 'Freeform or aspect-locked cropping for client decks, banners, and circular profile pictures. Export crystal-clear PNGs with 1-click downloads.',
    iconName: 'Crop',
    highlights: ['1:1, 4:5, 16:9 Presets', 'Circular Avatar Cutout', 'Zoom & Pan Canvas Controls', 'Lossless PNG Export'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop photo to crop...',
  },
  {
    id: 'convert-image',
    slug: 'convert-image',
    title: 'Image Format Converter (JPG, PNG, WebP)',
    shortTitle: 'Convert Image',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'Multi-Format',
    badgeColor: 'bg-indigo-50 text-indigo-700 border border-indigo-200/80',
    tagline: 'Convert between JPG, PNG, and WebP with background transparency fill options.',
    description: 'Batch convert image formats in seconds. Strip opaque backgrounds, fill transparent PNGs with custom studio colors, and export universal image files.',
    iconName: 'RefreshCw',
    highlights: ['Batch Multi-File Drop', 'Transparent Fill Picker', 'Instant Canvas Conversion', '100% In-Browser'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop images to convert format...',
  },
  {
    id: 'svg-to-png',
    slug: 'svg-to-png',
    title: 'SVG to PNG Vector Rasterizer',
    shortTitle: 'SVG to PNG',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'Retina Scale',
    badgeColor: 'bg-purple-50 text-purple-700 border border-purple-200/80',
    tagline: 'Rasterize SVG vectors to crystal clear PNGs at 1x, 2x, 4x, and 8x print resolution.',
    description: 'Drop SVG files or paste raw XML markup to render pixel-perfect raster graphics with alpha channel transparency and custom DPI multipliers.',
    iconName: 'Code',
    highlights: ['1x to 8x Retina Scaling', 'Raw XML Code Pasting', 'Lossless Alpha Channel', 'Zero Server Execution'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop SVG or paste vector markup...',
  },
  {
    id: 'heic-to-jpg',
    slug: 'heic-to-jpg',
    title: 'HEIC to JPG iPhone Photo Converter',
    shortTitle: 'HEIC to JPG',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'iPhone Photos',
    badgeColor: 'bg-teal-50 text-teal-700 border border-teal-200/80',
    tagline: 'Convert Apple iPhone .heic and .heif photos to universal JPG or PNG format in memory.',
    description: 'Bypass incompatible HEIC files from AirDrop or iPhone cameras. Decode photos instantly in browser RAM with zero third-party upload servers.',
    iconName: 'ImageIcon',
    highlights: ['Batch iPhone Photos', 'Direct JPG/PNG Export', 'Preserve High Color Dynamic Range', 'Zero Privacy Leakage'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop .heic or .heif photos...',
  },
  {
    id: 'remove-background',
    slug: 'remove-background',
    title: 'AI Background Remover (Transparent PNG)',
    shortTitle: 'Remove Background',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'AI Powered',
    badgeColor: 'bg-rose-50 text-rose-700 border border-rose-200/80',
    tagline: 'Isolate subjects and remove backgrounds with transparent PNG export and color backdrops.',
    description: 'Automatic in-browser foreground segmentation for headshots, product photography, and logos. Replace backgrounds with studio colors or export clean cutouts.',
    iconName: 'Sparkles',
    highlights: ['100% In-Browser Memory', 'Transparent Alpha PNG', 'Studio Backdrop Presets', 'Zero Cloud Uploads'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop photo to remove background...',
  },
  {
    id: 'image-to-text',
    slug: 'image-to-text',
    title: 'Image to Text OCR Scanner',
    shortTitle: 'Image to Text',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'OCR Scanner',
    badgeColor: 'bg-amber-50 text-amber-700 border border-amber-200/80',
    tagline: 'Extract text from receipts, book pages, infographics, and screenshots into editable copy.',
    description: 'Scan images and screenshots with client-side OCR. Automatically format extracted text, inspect confidence ratings, and copy to clipboard with 1 click.',
    iconName: 'FileText',
    highlights: ['In-Browser OCR', 'Paste from Clipboard (Cmd+V)', 'Editable Clean Text Area', '1-Click Copy & .txt Export'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop image or paste screenshot...',
  },
  {
    id: 'profile-photo-maker',
    slug: 'profile-photo-maker',
    title: 'Professional Profile Photo Studio',
    shortTitle: 'Profile Photo Maker',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'Avatar Studio',
    badgeColor: 'bg-cyan-50 text-cyan-700 border border-cyan-200/80',
    tagline: 'Craft LinkedIn, Twitter/X, and Slack avatars with circular framing, studio backdrops, and borders.',
    description: 'Transform candid selfies into professional studio headshots. Adjust framing, apply solid or gradient backdrops, and customize outline rings in real time.',
    iconName: 'Sliders',
    highlights: ['Circular Avatar Framing', 'Studio Backdrop Palettes', 'Outline Ring Customizer', 'High-Res Square Export'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop headshot or selfie photo...',
  },
  {
    id: 'watermark-image',
    slug: 'watermark-image',
    title: 'Watermark & Protect Photos',
    shortTitle: 'Watermark Image',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'Proof Protection',
    badgeColor: 'bg-violet-50 text-violet-700 border border-violet-200/80',
    tagline: 'Stamp confidential watermarks, copyright notices, or logo graphics over client photo proofs.',
    description: 'Protect creative assets before final invoice settlement. Add customizable text watermarks or logo overlays with opacity, rotation, and repeat tile patterns.',
    iconName: 'ShieldCheck',
    highlights: ['Text & Logo Watermarking', 'Full-Frame Tile Grid Mode', 'Opacity & Rotation Controls', 'Lossless Vector Stamping'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop image to apply watermark...',
  },
  {
    id: 'combine-images',
    slug: 'combine-images',
    title: 'Combine & Stitch Photos Together',
    shortTitle: 'Combine Images',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'Stitch & Grid',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Merge multiple photos side-by-side, stacked vertically, or arranged in a 2x2 collage grid.',
    description: 'Stitch before/after photos, project progress shots, or social media carousels into a single high-resolution composite image with adjustable border spacing.',
    iconName: 'Layers',
    highlights: ['Horizontal & Vertical Stitching', '2x2 Grid Layouts', 'Custom Border Padding', '1-Click High-Res Download'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop multiple photos to combine...',
  },
  {
    id: 'split-image',
    slug: 'split-image',
    title: 'Split Image into Grids & Carousels',
    shortTitle: 'Split Image',
    category: 'image_tools',
    categoryLabel: 'Image Tools',
    badge: 'Social Slices',
    badgeColor: 'bg-indigo-50 text-indigo-700 border border-indigo-200/80',
    tagline: 'Slice wide photos into multi-slide Instagram swipe carousels or 3x3 grid puzzle posts.',
    description: 'Partition panoramic photography and creative banners into seamless, consecutive square tiles for social media feeds with automated batch downloads.',
    iconName: 'Scissors',
    highlights: ['3-Slide Swipe Carousel', '3x3 Feed Puzzle Grid', 'Custom Row/Column Slicing', 'Batch Tile Download'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop image to slice into tiles...',
  },
  {
    id: 'elementor-migrator',
    slug: 'elementor-migrator',
    title: 'Elementor to Cora Website Migrator',
    shortTitle: 'Elementor Migrator',
    category: 'developer_embed',
    categoryLabel: 'Developer & Web',
    badge: '1-Click Migration',
    badgeColor: 'bg-zinc-100 text-zinc-900 border border-zinc-200/80',
    tagline: 'Analyze your WordPress & Elementor site for instant 1-click migration into Cora Studio Canvas.',
    description: 'Inspect live WordPress websites, validate Elementor JSON widget trees, test asset sideloading compatibility, and calculate performance gains when migrating to Cora Studio OS.',
    iconName: 'Globe',
    highlights: ['1-Click URL Compatibility', 'Elementor Version Detection', 'Asset Sideload Analyzer', 'Performance & Speed Compare'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Enter website URL (e.g. https://my-studio.com)...',
  },
];
