import { Calculator, Sparkles, Code, Scale, Receipt, QrCode } from 'lucide-react';

export interface ToolItem {
  id: string;
  slug: string;
  title: string;
  shortTitle: string;
  category: 'finance_tax' | 'retainer_agency' | 'ai_copy' | 'contracts_legal' | 'developer_embed' | 'payments_upi' | 'pdf_tools';
  categoryLabel: string;
  badge: string;
  badgeColor: string;
  tagline: string;
  description: string;
  iconName: string;
  highlights: string[];
  runs: string;
  inputPlaceholder: string;
}

export interface ToolCategoryBlock {
  id: string;
  title: string;
  subtitle: string;
  badgeTag: string;
  iconName: string;
  cardBg: string;
  iconBg: string;
  accentText: string;
  borderColor: string;
  borderHover: string;
  badgeBg: string;
  featuredToolName: string;
  featuredToolSlug: string;
}

export const TOOL_CATEGORY_BLOCKS: ToolCategoryBlock[] = [
  {
    id: 'pdf_tools',
    title: 'PDF Tools',
    subtitle: 'Merge, Split, eSign & Images',
    badgeTag: 'Client-Side',
    iconName: 'FileText',
    cardBg: 'bg-gradient-to-b from-[#FEF2F2] via-[#FEE2E2] to-white',
    iconBg: 'bg-rose-600 text-white shadow-[0_6px_16px_rgba(225,29,72,0.25)]',
    accentText: 'text-rose-600',
    borderColor: 'border-rose-100/90',
    borderHover: 'hover:border-rose-400 hover:shadow-[0_16px_36px_rgba(225,29,72,0.12)]',
    badgeBg: 'bg-rose-100/90 text-rose-700',
    featuredToolName: 'Merge PDF Files',
    featuredToolSlug: 'merge-pdf',
  },
  {
    id: 'finance_tax',
    title: 'GST & Tax Math',
    subtitle: '18% SAC 9983 & CGST/SGST',
    badgeTag: 'Tax Engine',
    iconName: 'Calculator',
    cardBg: 'bg-gradient-to-b from-[#EEF4FF] via-[#E4EEFE] to-white',
    iconBg: 'bg-indigo-600 text-white shadow-[0_6px_16px_rgba(79,70,229,0.25)]',
    accentText: 'text-indigo-600',
    borderColor: 'border-indigo-100/90',
    borderHover: 'hover:border-indigo-400 hover:shadow-[0_16px_36px_rgba(79,70,229,0.12)]',
    badgeBg: 'bg-indigo-100/90 text-indigo-700',
    featuredToolName: 'GST Calculator',
    featuredToolSlug: 'gst-calculator',
  },
  {
    id: 'retainer_agency',
    title: 'Agency Retainers',
    subtitle: 'Scope Buffers & Hourly Rates',
    badgeTag: 'Pricing Model',
    iconName: 'Receipt',
    cardBg: 'bg-gradient-to-b from-[#FFF7ED] via-[#FFEDD5] to-white',
    iconBg: 'bg-orange-500 text-white shadow-[0_6px_16px_rgba(249,115,22,0.25)]',
    accentText: 'text-orange-600',
    borderColor: 'border-orange-100/90',
    borderHover: 'hover:border-orange-400 hover:shadow-[0_16px_36px_rgba(249,115,22,0.12)]',
    badgeBg: 'bg-orange-100/90 text-orange-700',
    featuredToolName: 'Retainer Math',
    featuredToolSlug: 'retainer-calculator',
  },
  {
    id: 'contracts_legal',
    title: 'Legal Contracts',
    subtitle: 'Section 10A IT Act Clauses',
    badgeTag: 'Legal Vault',
    iconName: 'Scale',
    cardBg: 'bg-gradient-to-b from-[#F0F9FF] via-[#E0F2FE] to-white',
    iconBg: 'bg-blue-600 text-white shadow-[0_6px_16px_rgba(37,99,235,0.25)]',
    accentText: 'text-blue-600',
    borderColor: 'border-blue-100/90',
    borderHover: 'hover:border-blue-400 hover:shadow-[0_16px_36px_rgba(37,99,235,0.12)]',
    badgeBg: 'bg-blue-100/90 text-blue-700',
    featuredToolName: 'Contract Builder',
    featuredToolSlug: 'contract-builder',
  },
  {
    id: 'ai_copy',
    title: 'Studio AI Copy',
    subtitle: 'Brochures & Brief Prompts',
    badgeTag: 'AI Studio',
    iconName: 'Sparkles',
    cardBg: 'bg-gradient-to-b from-[#FFF1F2] via-[#FFE4E6] to-white',
    iconBg: 'bg-rose-500 text-white shadow-[0_6px_16px_rgba(244,63,94,0.25)]',
    accentText: 'text-rose-600',
    borderColor: 'border-rose-100/90',
    borderHover: 'hover:border-rose-400 hover:shadow-[0_16px_36px_rgba(244,63,94,0.12)]',
    badgeBg: 'bg-rose-100/90 text-rose-700',
    featuredToolName: 'Listing AI',
    featuredToolSlug: 'listing-ai',
  },
  {
    id: 'payments_upi',
    title: 'UPI 2.0 Invoicing',
    subtitle: 'Zero Fee Payment Links',
    badgeTag: '0% Gateway',
    iconName: 'QrCode',
    cardBg: 'bg-gradient-to-b from-[#FAF5FF] via-[#F3E8FF] to-white',
    iconBg: 'bg-purple-600 text-white shadow-[0_6px_16px_rgba(147,51,234,0.25)]',
    accentText: 'text-purple-600',
    borderColor: 'border-purple-100/90',
    borderHover: 'hover:border-purple-400 hover:shadow-[0_16px_36px_rgba(147,51,234,0.12)]',
    badgeBg: 'bg-purple-100/90 text-purple-700',
    featuredToolName: 'Dynamic UPI QR',
    featuredToolSlug: 'upi-qr-generator',
  },
  {
    id: 'developer_embed',
    title: 'Embed Widgets',
    subtitle: 'Framer & Webflow Forms',
    badgeTag: 'Developer',
    iconName: 'Code',
    cardBg: 'bg-gradient-to-b from-[#F0FDFA] via-[#CCFBF1] to-white',
    iconBg: 'bg-teal-600 text-white shadow-[0_6px_16px_rgba(13,148,136,0.25)]',
    accentText: 'text-teal-600',
    borderColor: 'border-teal-100/90',
    borderHover: 'hover:border-teal-400 hover:shadow-[0_16px_36px_rgba(13,148,136,0.12)]',
    badgeBg: 'bg-teal-100/90 text-teal-700',
    featuredToolName: 'Embed Builder',
    featuredToolSlug: 'embed-builder',
  },
];

export const TOOL_CATEGORIES = [
  { id: 'all', label: 'All Tools', count: 34 },
  { id: 'pdf_tools', label: 'PDF Tools', count: 28 },
  { id: 'finance_tax', label: 'Finance & Tax', count: 2 },
  { id: 'contracts_legal', label: 'Contracts & Legal', count: 1 },
  { id: 'ai_copy', label: 'AI & Copywriting', count: 1 },
  { id: 'developer_embed', label: 'Developer & Embeds', count: 2 },
];

export const TOOLS_DATA: ToolItem[] = [
  {
    id: 'gst-calculator',
    slug: 'gst-calculator',
    title: 'Indian GST & B2B Tax Calculator',
    shortTitle: 'GST Tax Calculator',
    category: 'finance_tax',
    categoryLabel: 'Finance & Tax',
    badge: 'Popular in India',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Instant 18%, 12%, 5%, 28% tax breakdown with CGST/SGST vs IGST segregation.',
    description: 'Calculate GST inclusive and exclusive pricing, split intra-state vs inter-state tax liabilities, and generate compliant breakdown summaries for your client proposals.',
    iconName: 'Calculator',
    highlights: ['18% SAC 9983 Support', 'CGST & SGST 50/50 Split', 'IGST Inter-State Toggle', '1-Click Breakdown Copy'],
    runs: 'Zero Login Required',
    inputPlaceholder: '₹50,000',
  },
  {
    id: 'retainer-calculator',
    slug: 'retainer-calculator',
    title: 'Service Retainer & Scope Buffer Calculator',
    shortTitle: 'Retainer Math Calculator',
    category: 'finance_tax',
    categoryLabel: 'Finance & Tax',
    badge: 'Agency Tool',
    badgeColor: 'bg-blue-50 text-blue-700 border border-blue-200/80',
    tagline: 'Calculate optimal monthly agency retainer tiers and billable hourly baseline rates.',
    description: 'Input your revenue targets, billable client capacity, and team overheads to calculate sustainable monthly retainer packages with automatic 20% scope creep buffers.',
    iconName: 'Receipt',
    highlights: ['Hourly to Retainer Conversion', '20% Scope Creep Buffer', 'Capacity Utilization Math', 'Client Tier Allocation'],
    runs: 'Zero Login Required',
    inputPlaceholder: '₹3,00,000 / mo',
  },
  {
    id: 'contract-builder',
    slug: 'contract-builder',
    title: 'Indian IT Act 2000 Contract Clause Builder',
    shortTitle: 'Contract Clause Builder',
    category: 'contracts_legal',
    categoryLabel: 'Contracts & Legal',
    badge: 'IT Act 2000 Compliant',
    badgeColor: 'bg-slate-100 text-slate-800 border border-slate-200/80',
    tagline: 'Generate legally binding contract clauses, milestone escrow terms, and NDAs.',
    description: 'Build customized Indian legal agreements with Section 10A digital signature recognition, SHA-256 tamper-evident integrity clauses, and 18% GST tax provisions.',
    iconName: 'Scale',
    highlights: ['Section 10A Electronic Signatures', 'Scope Lock & Milestone Escrow', 'IP & Copyright Assignment', 'Mutual Non-Disclosure Terms'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Client: Acme Corp, Retainer: ₹1,50,000...',
  },
  {
    id: 'listing-ai',
    slug: 'listing-ai',
    title: 'Real Estate & Studio Listing AI Generator',
    shortTitle: 'Listing AI Generator',
    category: 'ai_copy',
    categoryLabel: 'AI & Copywriting',
    badge: 'AI Powered',
    badgeColor: 'bg-purple-50 text-purple-700 border border-purple-200/80',
    tagline: 'Turn raw property or shoot details into high-converting marketing copy and client briefs.',
    description: 'Leverage domain-trained AI prompts to generate luxury real estate brochures, Instagram captions, commercial shoot briefs, and client welcome decks in seconds.',
    iconName: 'Sparkles',
    highlights: ['3 Output Formats', 'Commercial & Residential Modes', 'Tone Tuning (Luxury / Minimal)', 'Multi-Platform Export'],
    runs: 'Zero Login Required',
    inputPlaceholder: '3BHK Sea-Facing Penthouse, Bandra West...',
  },
  {
    id: 'upi-qr-generator',
    slug: 'upi-qr-generator',
    title: 'Dynamic UPI QR & Payment Intent Generator',
    shortTitle: 'UPI QR Generator',
    category: 'developer_embed',
    categoryLabel: 'Developer & Embeds',
    badge: 'UPI 2.0 Ready',
    badgeColor: 'bg-teal-50 text-teal-700 border border-teal-200/80',
    tagline: 'Generate instant UPI QR codes with custom invoice amount, payee VPA & transaction note.',
    description: 'Create zero-fee dynamic UPI payment links and printable QR codes for Indian bank settlements. Compatible with Google Pay, PhonePe, Paytm, and BHIM.',
    iconName: 'QrCode',
    highlights: ['Zero Payment Gateway Fees (0%)', 'Exact Invoice Amount Embedding', 'Instant Client-Side QR Render', 'PNG & SVG Download'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'business@okhdfcbank',
  },
  {
    id: 'embed-builder',
    slug: 'embed-builder',
    title: 'Autonomous AI Copilot & Embed Builder',
    shortTitle: 'Embed Widget Builder',
    category: 'developer_embed',
    categoryLabel: 'Developer & Embeds',
    badge: 'Developer Tool',
    badgeColor: 'bg-amber-50 text-amber-700 border border-amber-200/80',
    tagline: 'Generate embeddable AI booking widgets for Framer, Webflow, WordPress & Shopify.',
    description: 'Customize zero-code iframe embeds to capture leads, book call slots, and calculate quotes directly on your marketing site with auto-sync to your Cora workspace.',
    iconName: 'Code',
    highlights: ['Zero-Code iFrame Snippet', 'Framer & Webflow Ready', 'Light / Dark Mode Customization', 'Direct Webhook Integration'],
    runs: 'Zero Login Required',
    inputPlaceholder: '<iframe src="https://heycora.in/embed/..." />',
  },
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    title: 'Merge PDF Files Online Free',
    shortTitle: 'Merge PDF Files',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: '100% Client-Side',
    badgeColor: 'bg-rose-50 text-rose-700 border border-rose-200/80',
    tagline: 'Combine multiple PDF documents into a single organized file in seconds.',
    description: 'Merge invoices, contracts, proposals, and client portfolios with simple drag-and-drop reordering. 100% private and runs entirely in your browser.',
    iconName: 'Files',
    highlights: ['Zero Server Uploads', 'Drag & Drop Page Reorder', 'Instant In-Browser Merge', 'No File Size Limits'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop PDF files here to merge...',
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    title: 'Split & Extract PDF Pages',
    shortTitle: 'Split & Extract PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'Instant Extract',
    badgeColor: 'bg-amber-50 text-amber-700 border border-amber-200/80',
    tagline: 'Separate PDF pages or extract custom page ranges into individual documents.',
    description: 'Extract specific pages, isolate signed execution sheets, or split heavy deliverables into lightweight client PDF packets without quality loss.',
    iconName: 'Scissors',
    highlights: ['Custom Range Extraction', 'Single Page Isolation', '100% In-Browser Engine', 'Instant Zip / File Download'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'e.g. 1-3, 5, 8-10',
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    title: 'Rotate PDF Pages Permanently',
    shortTitle: 'Rotate PDF Pages',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: '90° / 180° / 270°',
    badgeColor: 'bg-blue-50 text-blue-700 border border-blue-200/80',
    tagline: 'Rotate orientation of individual or all pages in your PDF document permanently.',
    description: 'Fix upside-down scans, adjust architectural plan orientation, and align landscape agreements before sending to clients.',
    iconName: 'RotateCw',
    highlights: ['Selective Page Rotation', 'Clockwise & Counter-Clockwise', 'Permanent Metadata Save', 'Zero Cloud Transmission'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Select pages to rotate...',
  },
  {
    id: 'images-to-pdf',
    slug: 'images-to-pdf',
    title: 'Images to PDF Converter (JPG, PNG, WebP)',
    shortTitle: 'Images to PDF Converter',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'High-Res Output',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Convert photos, design mockups, and receipts into a unified high-res PDF.',
    description: 'Bundle shoot photos, invoice receipts, and property site inspections into clean, shareable client PDF decks with margin and orientation controls.',
    iconName: 'ImageIcon',
    highlights: ['JPG, PNG, WebP & HEIC', 'Custom Page Sizing (A4/Letter)', 'Margin & Spacing Controls', 'Lossless Quality Retention'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop photo assets here...',
  },
  {
    id: 'esign-pdf',
    slug: 'esign-pdf',
    title: 'Digital eSign PDF & Contract Signer',
    shortTitle: 'Digital eSign PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'IT Act 2000 Ready',
    badgeColor: 'bg-indigo-50 text-indigo-700 border border-indigo-200/80',
    tagline: 'Draw or type your signature and place it securely on any PDF agreement.',
    description: 'Sign NDAs, client estimates, vendor agreements, and invoices directly in browser with timestamped audit markers.',
    iconName: 'FileCheck',
    highlights: ['Draw or Type Signatures', 'Stamp & Date Placeholders', 'Section 10A IT Act Compliant', 'No Account Required'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Upload document to sign...',
  },
  {
    id: 'watermark-pdf',
    slug: 'watermark-pdf',
    title: 'Add Watermark to PDF Documents',
    shortTitle: 'Add Watermark to PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'Draft & Confidential',
    badgeColor: 'bg-violet-50 text-violet-700 border border-violet-200/80',
    tagline: 'Stamp text or image watermarks across PDF pages with opacity controls.',
    description: 'Protect draft contracts, sensitive client proposals, and preview design proofs with custom diagonal text stamps and confidentiality markers.',
    iconName: 'Stamp',
    highlights: ['Custom Text & Opacity', 'Diagonal & Center Placement', 'Batch Page Watermarking', 'Zero Server File Retention'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'e.g. CONFIDENTIAL / DRAFT',
  },
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    title: 'Compress PDF Online Free',
    shortTitle: 'Compress PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'Popular',
    badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200/80',
    tagline: 'Reduce PDF file size up to 70% in seconds while preserving crisp vector text.',
    description: 'Compress heavy client proposals, pitch decks, and invoices to under 5MB for instant WhatsApp sharing and email attachments. 100% private in-browser execution.',
    iconName: 'Minimize2',
    highlights: ['3 Compression Tiers', 'Up to 70% Size Reduction', 'Live Before/After Metrics', 'Zero Server Uploads'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop PDF file here to compress...',
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    title: 'Word to PDF Converter Online',
    shortTitle: 'Word to PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'New',
    badgeColor: 'bg-blue-50 text-blue-700 border border-blue-200/80',
    tagline: 'Transform raw document text, terms, and drafts into clean typeset A4 PDF files.',
    description: 'Publish memos, client estimates, and agreements into standardized PDF documents with automated word wrapping and clean typography.',
    iconName: 'FileType',
    highlights: ['Automated Word Wrapping', 'Clean A4 Typesetting', 'Standard Font Embeds', 'Instant 1-Click Download'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Paste or upload document text...',
  },
  {
    id: 'number-pdf',
    slug: 'number-pdf',
    title: 'Add Page Numbers to PDF',
    shortTitle: 'Add Page Numbers',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'Custom Headers/Footers',
    badgeColor: 'bg-purple-50 text-purple-700 border border-purple-200/80',
    tagline: 'Stamp automated pagination headers and footers with customizable format and offsets.',
    description: 'Format legal briefs, client contracts, and multi-page technical decks with uniform page numbers (Bottom-Center, Bottom-Right, "Page X of Y").',
    iconName: 'Hash',
    highlights: ['Page X of Y & Numeric Formats', 'Position Presets', 'Custom Starting Page', 'Lossless Vector Stamping'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop PDF to add page numbers...',
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    title: 'Remove Pages from PDF',
    shortTitle: 'Remove Pages',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: '1-Click Delete',
    badgeColor: 'bg-red-50 text-red-700 border border-red-200/80',
    tagline: 'Delete unwanted sheets, blank pages, or outdated appendixes from your PDF.',
    description: 'Select pages to delete or enter custom page spans with visual feedback and export a pristine, compact PDF document in seconds.',
    iconName: 'Trash2',
    highlights: ['Visual Page Chips', 'Custom Range Inputs', 'Instant Re-export', '100% In-Memory'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'e.g. 2, 4-6',
  },
  {
    id: 'ai-pdf-summarizer',
    slug: 'ai-pdf-summarizer',
    title: 'AI PDF Summarizer & Contract Scanner',
    shortTitle: 'AI PDF Summarizer',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    badge: 'AI Radar',
    badgeColor: 'bg-amber-50 text-amber-700 border border-amber-200/80',
    tagline: 'Scan contracts, find hidden risk clauses, and extract executive summaries in seconds.',
    description: 'Instantly audit commercial proposals and vendor agreements for liabilities, payment schedules, and termination penalties with Cora AI intelligence.',
    iconName: 'Bot',
    highlights: ['Clause Risk Radar', 'Executive Summary', 'Action Item Breakdown', 'Bridge to Cora AI Co-Founder'],
    runs: 'Zero Login Required',
    inputPlaceholder: 'Drop PDF document to inspect...',
  },
];
